# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "context_bases",
    hdrs = [
        "i_context.hpp",
        "i_streaming_context.hpp",
        "i_streaming_output_context.hpp",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = [
        "//score/crypto/src/api/common:crypto_common",
        "@score_baselibs//score/language/futurecpp",
        "@score_baselibs//score/result",
    ],
)

cc_library(
    name = "crypto_contexts",
    hdrs = [
        "i_cipher_context.hpp",
        "i_hash_context.hpp",
        "i_key_management_context.hpp",
        "i_mac_context.hpp",
        "i_random_context.hpp",
        "i_sign_context.hpp",
        "i_verify_signature_context.hpp",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = [
        ":context_bases",
        "//score/crypto/src/api/common:crypto_common",
        "//score/crypto/src/api/config:context_configs",
        "//score/crypto/src/api/objects:crypto_objects",
        "@score_baselibs//score/language/futurecpp",
        "@score_baselibs//score/result",
    ],
)

cc_library(
    name = "crypto_contexts_impl",
    srcs = [
        "src/cipher_context_impl.cpp",
        "src/hash_context_impl.cpp",
        "src/key_management_context_impl.cpp",
        "src/mac_context_impl.cpp",
        "src/random_context_impl.cpp",
        "src/sign_context_impl.cpp",
        "src/verify_signature_context_impl.cpp",
    ],
    hdrs = [
        "src/cipher_context_impl.hpp",
        "src/hash_context_impl.hpp",
        "src/key_management_context_impl.hpp",
        "src/mac_context_impl.hpp",
        "src/random_context_impl.hpp",
        "src/sign_context_impl.hpp",
        "src/verify_signature_context_impl.hpp",
    ],
    includes = ["."],
    visibility = ["//:__subpackages__"],
    deps = [
        ":crypto_contexts",
        "//score/crypto/src/api:operations",
        "//score/crypto/src/api/common:crypto_common",
        "//score/crypto/src/api/common:release_callback_iface",
        "//score/crypto/src/api/control_plane",
        "//score/crypto/src/api/data_plane:data_plane_client",
    ],
)
