# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# =============================================================================
# Context interfaces below are not yet active (IPC implementation pending).
# Each is defined in this directory and declared in i_crypto_context.hpp.
# =============================================================================

load("@rules_cc//cc:defs.bzl", "cc_library")

# -- AEAD --
# cc_library(
#     name = "aead_context",
#     hdrs = ["i_aead_context.hpp"],
#     deps = [
#         "//score/crypto/src/api/contexts:context_bases",
#         "//score/crypto/src/api/common:crypto_common",
#         "@score_baselibs//score/result",
#     ],
# )

# -- Certificate management + verification + CSR --
# cc_library(
#     name = "certificate_contexts",
#     hdrs = [
#         "i_certificate_management_context.hpp",
#         "i_certificate_verification_context.hpp",
#         "i_csr_generation_context.hpp",
#     ],
#     deps = [
#         "//score/crypto/src/api/contexts:context_bases",
#         "//score/crypto/src/api/common:crypto_common",
#         "//score/crypto/src/api/future/certificate:crypto_certificate",
#         "@score_baselibs//score/result",
#     ],
# )
