# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# =============================================================================
# FUTURE: Config headers below are not yet in scope. To activate, move the
#         .hpp back to //score/crypto/src/api/config/ and add to context_configs.
# =============================================================================

load("@rules_cc//cc:defs.bzl", "cc_library")

# cc_library(
#     name = "future_context_configs",
#     hdrs = [
#         "aead_context_config.hpp",
#         "certificate_context_config.hpp",
#         "certificate_verification_context_config.hpp",
#         "csr_generation_context_config.hpp",
#     ],
#     deps = [
#         "//score/crypto/src/api/common:crypto_common",
#     ],
# )
