# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: Build and Test (QNX)

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
  merge_group:
    types: [checks_requested]
  workflow_call:
jobs:
  qnx-build:
    name: Build and Test ${{ matrix.bazel-config }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - bazel-config: x86_64-qnx
            bazel-test-target: >-
              //score/... //tests/...
            extra-bazel-test-flags: "--test_timeout=180,900,2700,10800" # Increase default test timeout by factor 3
          - bazel-config: aarch64-qnx
            bazel-test-target: >-
              //score/... //tests/...
            extra-bazel-test-flags: "--test_timeout=180,900,2700,10800" # Increase default test timeout by factor 3
    uses: eclipse-score/cicd-workflows/.github/workflows/qnx-build.yml@88cb460c47cb49efeb25cd7b73c8945dd1c5bce2
    permissions:
      contents: read
      pull-requests: read
    with:
      bazel-target: "//score/... //tests/..."
      bazel-config: ${{ matrix.bazel-config }}
      bazel-test-target: ${{ matrix.bazel-test-target }}
      extra-bazel-test-flags: ${{ matrix.extra-bazel-test-flags }}
      credential-helper: ".github/tools/qnx_credential_helper.py"
      bazel-disk-cache: ${{ matrix.bazel-config }}
    secrets:
      score-qnx-license: ${{ secrets.SCORE_QNX_LICENSE }}
      score-qnx-user: ${{ secrets.SCORE_QNX_USER }}
      score-qnx-password: ${{ secrets.SCORE_QNX_PASSWORD }}
